#! /usr/bin/env python3

import fitz
import glob
from PIL import Image
import argparse
import os

def make_pdf(path, name):
    document = fitz.open()

    extensions = ["*.jpg", "*.png"]
    image_list = []

    for extension in extensions:
        for file in glob.glob(path + extension):
            image_list.append(file)

    image_list.sort()

    for image in image_list:
        im = Image.open(image)
        w, h = im.size
        new_page = document.newPage(width = w, height = h)
        page = document[-1]
        page.insertImage((0, 0, w, h), image)
        im.close()

    document.save(path + name)
    document.close()

def Main():
    parser = argparse.ArgumentParser(
        description = "Easily convert your hentais from folders of images to one pdf file"
        )
    parser.add_argument(
        "-m",
        "--make",
        nargs = 2,
        metavar = ('path', 'name'),
        required = False,
        help = "provide abosule or relative path to a folder with your hentai and a name you want to give for the generated pdf file"
        )
    parser.add_argument(
        "-mc",
        "--makecurrent",
        nargs = 1,
        metavar = 'name',
        required = False,
        help = "open terminal in the folder with your hentai and provide a name you want to give for the generated pdf file"
        )
    args = parser.parse_args()

    if args.makecurrent:
        path = os.getcwd()
        name = args.makecurrent[0]
    elif args.make[0].startswith("/"):
        path = args.make[0]
        name = args.make[1]
    elif args.make[0].startswith("/") == False:
        path = os.getcwd() + "/" + args.make[0]
        name = args.make[1]

    if path.endswith("/") == False:
        path = path + "/"

    make_pdf(path, name)

if __name__ == "__main__":
    Main()
